[project]
name = "pytesseract-streamlit"
version = "0.1.0"
description = "A streamlit interface to use the Pytesseract package"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pytesseract>=0.3.13",
    "streamlit>=1.45.1",
]
license="MIT"

